UCLA scl 1.0
# Created : 06/20/2019 01:55:25

NumRows : 299

CoreRow Horizontal
	Coordinate   : 2436
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2448
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2460
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2472
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2484
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2496
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2508
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2520
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2532
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2544
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2556
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2568
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2580
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2592
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2604
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2616
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2628
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2640
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2652
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2664
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2676
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2688
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2700
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2712
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2724
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2736
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2748
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2760
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2772
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2784
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2796
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2808
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2820
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2832
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2844
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2856
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2868
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2880
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2892
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2904
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2916
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2928
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2940
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2952
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2964
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2976
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 2988
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 3000
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 3012
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 3024
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 3036
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 3048
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 3060
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 3200
End
CoreRow Horizontal
	Coordinate   : 3072
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3084
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3096
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3108
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3120
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3132
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3144
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3156
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3168
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3180
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3192
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3204
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3216
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3228
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3240
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3252
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3264
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3276
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3288
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3300
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3312
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3324
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3336
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3348
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3360
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3372
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3384
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3396
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3408
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3420
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3432
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3444
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3456
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3468
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3480
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3492
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3504
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3516
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3528
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3540
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3552
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3564
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3576
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3588
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3600
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3612
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3624
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3636
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3648
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3660
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3672
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3684
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3696
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3708
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3720
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3732
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3744
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3756
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3768
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3780
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3792
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3804
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3816
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3828
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3840
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3852
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3864
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3876
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3888
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3900
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3912
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3924
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3936
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3948
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3960
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3972
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3984
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 3996
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4008
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4020
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4032
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4044
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4056
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4068
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4080
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4092
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4104
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4116
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4128
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4140
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4152
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4164
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4176
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4188
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4200
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4212
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4224
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4236
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4248
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4260
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4272
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4284
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4296
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4308
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4320
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4332
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4344
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4356
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4368
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4380
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4392
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4404
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4416
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4428
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4440
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4452
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4464
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4476
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4488
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4500
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4512
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4524
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4536
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4548
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4560
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4572
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4584
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4596
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4608
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4620
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4632
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4644
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4656
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4668
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4680
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4692
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4704
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4716
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4728
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4740
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4752
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4764
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4776
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4788
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4800
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4812
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4824
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4836
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4848
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4860
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4872
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4884
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4896
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4908
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4920
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4932
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4944
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4956
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4968
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4980
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 4992
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5004
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5016
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5028
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5040
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5052
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5064
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5076
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5088
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5100
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5112
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5124
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5136
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5148
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5160
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5172
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5184
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5196
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5208
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5220
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5232
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5244
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5256
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5268
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5280
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5292
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5304
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5316
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5328
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5340
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5352
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5364
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5376
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5388
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5400
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5412
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5424
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5436
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5448
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5460
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5472
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5484
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5496
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5508
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5520
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5532
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5544
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5556
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5568
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5580
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5592
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5604
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5616
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5628
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5640
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5652
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5664
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5676
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5688
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5700
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5712
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5724
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5736
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5748
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5760
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5772
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5784
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5796
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5808
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5820
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5832
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5844
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5856
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5868
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5880
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5892
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5904
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5916
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5928
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5940
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5952
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5964
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5976
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 5988
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 6000
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : FS
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
CoreRow Horizontal
	Coordinate   : 6012
	Height       : 12
	Sitewidth    : 1.35
	Sitespacing  : 1
	Siteorient   : N
	Sitesymmetry : Y
	SubrowOrigin : 0	NumSites : 6582
End
